In [1]:
import numpy as np

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 24.9.1

Please update conda by running

    $ conda update -n base -c defaults conda




In [4]:
# concatenation of two list
a = [2,4,5,6,8]
b = [5,4,5,2,4]
a+b

[2, 4, 6, 8, 5, 4, 5, 2, 4]

In [6]:
# Add two list
# for loop
# zip function is used
a = [2,4,5,6,8]
b = [5,4,5,2,4]
result=[] 
for first,second in zip (a,b):
    result.append(first+second)
result

[7, 8, 10, 8, 12]

In [8]:
import numpy as np

In [9]:
# add using numpy function
# np.array([a,b,c,d])
a=np.array([2,4,5,6,8])
b=np.array([5,4,5,2,4])
a+b

array([ 7,  8, 10,  8, 12])

In [10]:
# check type of Array
a=np.array([2,4,5,6,8])
type(a)

numpy.ndarray

In [11]:
# check data type and size in bits
a.dtype

dtype('int32')

In [13]:
f=np.array([1.2,4.5,7.8,2.3])
f.dtype

dtype('float64')

In [14]:
#little-endian

In [19]:
# Replace value in array using index no
x=np.array([89,34,56,87])
x[0]=76
x

array([76, 34, 56, 87])

In [20]:
# When we try replacing with float value
# It won't work as data types are not similar
x[2]=23.6
x

array([76, 34, 23, 87])

In [21]:
# to check dimension
x.ndim

1

In [22]:
# to check the shape
# it shows only 4 because it is one dimensional
x.shape

(4,)

In [23]:
# shows 4 because it has 4 elements
x.size

4

In [24]:
# shows 5 as it has 5 elements
x=np.array([89,34,56,87,90])
x.size

5

In [43]:
np.ones(shape, dtype=None, order = 'C')

NameError: name 'shape' is not defined

In [45]:
np.zeros()
np.empty()

TypeError: zeros() missing required argument 'shape' (pos 1)

In [30]:
# create 5 shape 1D array of one elements
arr1=np.ones(5,)
arr1

array([1., 1., 1., 1., 1.])

In [42]:
# create 5 shape 2D array of one elements
# np.ones([])--syntax
arr1=np.ones([5,2])
arr1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
arr1=np.ones([4,4])
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
arr1=np.empty([4,1])
arr1

array([[1.2],
       [4.5],
       [7.8],
       [2.3]])

In [55]:
# put range in array as per the index no
np.arange(5)

array([0, 1, 2, 3, 4])

In [57]:
# np.arange([start],stop,[step,]),dtype=None,*,like=None

SyntaxError: cannot assign to function call (Temp/ipykernel_7220/4016264048.py, line 2)

In [58]:
# print according to start stop and step
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [60]:
a=np.array([33,2,3,4])
b=np.array([5,5,72,56])
a+b

array([38,  7, 75, 60])

In [61]:
a-b

array([ 28,  -3, -69, -52])

In [62]:
a*b

array([165,  10, 216, 224])

In [63]:
a/b

array([6.6       , 0.4       , 0.04166667, 0.07142857])

In [64]:
a**b

array([  39135393,         32, -919996767,          0], dtype=int32)

In [69]:
# create two arrays each has 5 values, one starts at 100, other at ends at 255. 
# u decide how to get 5 values for array and add them using numpy
a=np.arange(100,255,35)
a

array([100, 135, 170, 205, 240])

In [71]:
arr2=np.array([[1,2],[7,8]])
arr2

array([[1, 2],
       [7, 8]])

In [73]:
arr3=np.array([[1,2,3],[5,6,8],[9,3,4]])
arr3

array([[1, 2, 3],
       [5, 6, 8],
       [9, 3, 4]])

In [74]:
arr2

array([[1, 2],
       [7, 8]])

In [76]:
# print elements from 2 by 2 vector by index no
arr2[0,0]

1

In [77]:
arr2[1,1]

8

In [79]:
# Replace value using index no
arr2[1,0]=9
arr2

array([[1, 2],
       [9, 8]])

In [81]:
# We can't assign float as it is a different data type
arr2[1,0]=55.67
arr2

array([[ 1,  2],
       [55,  8]])

In [82]:
# Print whole row at index 0
arr2[0]

array([1, 2])

In [86]:
# Print whole index at index 2
arr5=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr5[2]

array([7, 8, 9])

# Slicing

In [87]:
# arr[lower:upper:step] -- syntax

In [88]:
x=np.array([10,23,4,56,89,34,13])

In [89]:
# Print using slicing function
# start from index 1 and end at 3
# it doesn't print the upper limit, only prints lower limit and between
x[1:3]

array([23,  4])

In [91]:
# it doesn't print the upper limit
x[:-3]

array([10, 23,  4, 56])

In [92]:
# Print everything after index 3
x[3:]

array([56, 89, 34, 13])

In [93]:
# Print everything start to end with two step
x[::2]

array([10,  4, 89, 13])

In [95]:
# SLice using arrslice function
arrslice = np.array([44,55,66,55,55,77,88,55,44,66,55,])
y = arrslice[0:12:2]
y

array([44, 66, 55, 88, 44, 55])

In [101]:
# Slice from index 4 from end to index 1 from end
arrslice = np.array([1,2,3,4,5,6,7])
z = arrslice[-4:]
z

array([4, 5, 6, 7])

In [102]:
# Slicing from 3D Array
# row is first index
# col is second index
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [103]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [109]:
arr[1:,0:1]

array([[4],
       [7]])

In [116]:
# EXERCISE 1
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
# print data type
type(np.arange(0,11))

numpy.ndarray

In [124]:
# change dtype to float
a=np.arange(0,11),dtype=float, close=None

SyntaxError: cannot assign to function call (Temp/ipykernel_7220/3937735597.py, line 2)

In [132]:
# Exercise 2 - extract odd numbers
arr= np.array([0,1,2,3,4,5,6,7,8,9])
arr[1::2]


array([1, 3, 5, 7, 9])

In [133]:
# Keep original and create a copy and make changes in new file
a = np.array([21,22,23,21,23])
b=a
c=np.copy(a)
c

array([21, 22, 23, 21, 23])

In [135]:
a[1]=90
a

array([21, 90, 23, 21, 23])

In [136]:
b

array([21, 90, 23, 21, 23])

In [137]:
c

array([21, 22, 23, 21, 23])

In [138]:
# Sorting
sample_array=np.array([2,0,5,1,9,6,5,3,7,4,6,8])

In [139]:
# Sort in descending order
np.sort(sample_array)[::-1]

array([9, 8, 7, 6, 6, 5, 5, 4, 3, 2, 1, 0])

In [140]:
# Sort in ascending order
np.sort(sample_array)

array([0, 1, 2, 3, 4, 5, 5, 6, 6, 7, 8, 9])

In [142]:
sample_array = np.arange(15)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [143]:
# Shape 1d to 3d using reshape function
reshaped_array = sample_array.reshape(3,5)
reshaped_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [145]:
# Transposing matrices using transpose function i.e row to col, col to row
reshaped_array.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [147]:
reversed_array1 = np.flip(sample_array)
reversed_array1

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [150]:
# Flip rows
sample_2darray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
reversed_2darray = np.flip(sample_2darray)
reversed_2darray

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [152]:
# Flip vertically
reversed_2darray1 = np.flip(sample_2darray, axis=0)
reversed_2darray1

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [154]:
# go back after reshape
a=np.array([[1,2],[3,4]])
a.flatten()

array([1, 2, 3, 4])